import random
from models.one_letter_one_sentence import OneLetterOneSentence

class LetterServices:

    def __init__(self):
        pass

    def load_content_by_letter(self):
        phrases = [
                "Tu vas apprendre une bonne nouvelle cet après-midi.",
                "Tu vas découvrir une surprise par hasard.",
                "Il se peut que tu rencontres un sourire sincère dans la matinée.",
                "Tu vas éviter un malentendu au travail.",
                "Quelqu'un va te parler de ton potentiel pendant un appel.",
                "Aujourd'hui, attends-toi à une idée brillante en rentrant chez toi.",
                "Prépare-toi à un souvenir marquant au détour d'une conversation.",
                "Tu vas recevoir un compliment mérité en ligne.",
                "Tu pourrais ressentir un regain d'énergie en faisant du sport.",
                "Il est probable que tu vives une nouvelle rencontre ce soir.",
                "Un événement inattendu impliquera une solution dans la matinée.",
                "Tu vas perdre un moment de doute grâce à un ami.",
                "Tu vas rencontrer une personne inspirante au travail.",
                "Tu vas éviter un obstacle à franchir en te promenant.",
                "Tu vas gagner une opportunité dans un rêve.",
                "Tu vas réfléchir à une erreur à corriger en lisant un message.",
                "Tu vas découvrir un message important cet après-midi.",
                "Il se peut que tu rencontres une surprise inattendue en ligne.",
                "Un malentendu sera évité au détour d'une conversation.",
                "Tu vas recevoir un appel inattendu pendant un appel.",
                "Aujourd'hui, attends-toi à une coïncidence troublante au travail.",
                "Prépare-toi à une idée brillante dans la matinée.",
                "Quelqu'un va te parler de tes progrès ce soir.",
                "Tu vas rencontrer un défi motivant en te promenant.",
                "Tu vas apprendre une leçon précieuse devant un café.",
                "Tu vas découvrir une personne inspirante cet après-midi.",
                "Il se peut que tu rencontres une solution inattendue au travail.",
                "Tu pourrais ressentir un moment de calme en rentrant chez toi.",
                "Tu vas éviter un problème mineur par hasard.",
                "Tu vas gagner une réflexion personnelle dans un rêve.",
                "Il est probable que tu vives une surprise agréable pendant un appel.",
                "Prépare-toi à une opportunité unique en lisant un message.",
                "Tu vas recevoir un compliment mérité au détour d'une conversation.",
                "Un souvenir marquant refera surface ce soir.",
                "Tu vas découvrir un regain d'énergie au travail.",
                "Il se peut que tu rencontres une personne inspirante grâce à un ami.",
                "Aujourd'hui, attends-toi à une bonne nouvelle en te promenant.",
                "Tu vas éviter une erreur à corriger ce soir.",
                "Tu vas gagner un sourire sincère devant un café.",
                "Prépare-toi à vivre un moment de doute pendant un appel.",
                "Un événement inattendu impliquera un message important dans la matinée.",
                "Tu vas apprendre une solution en ligne.",
                "Tu pourrais ressentir un obstacle à franchir ce soir.",
                "Quelqu'un va te parler d'un souvenir marquant au travail.",
                "Tu vas rencontrer une surprise agréable cet après-midi.",
                "Tu vas découvrir un malentendu à résoudre par hasard.",
                "Il est probable que tu vives un regain d'énergie grâce à un ami.",
                "Tu vas éviter un défi au détour d'une conversation.",
                "Aujourd'hui, attends-toi à une idée brillante au travail.",
                "Tu vas recevoir un appel inattendu en te promenant.",
                "Prépare-toi à une réflexion personnelle devant un café.",
                "Tu vas gagner une surprise inattendue dans un rêve.",
                "Tu vas apprendre un message important pendant un appel.",
                "Tu vas découvrir une solution en lisant un message.",
                "Tu vas rencontrer une personne inspirante au détour d'une conversation.",
                "Il se peut que tu rencontres une opportunité unique ce soir.",
                "Quelqu'un va te parler de tes qualités aujourd'hui.",
                "Tu vas recevoir une bonne nouvelle grâce à un ami.",
                "Aujourd'hui, attends-toi à un souvenir marquant cet après-midi.",
                "Tu vas éviter un problème mineur au travail.",
                "Prépare-toi à un moment de calme en rentrant chez toi.",
                "Tu vas gagner une idée brillante dans la matinée.",
                "Tu vas rencontrer un sourire sincère au détour d'une conversation.",
                "Il est probable que tu vives une surprise agréable ce soir.",
                "Tu pourrais ressentir une nouvelle rencontre par hasard.",
                "Tu vas découvrir un défi motivant en te promenant.",
                "Un événement inattendu impliquera une réflexion personnelle en ligne.",
                "Tu vas recevoir un compliment mérité pendant un appel.",
                "Aujourd'hui, attends-toi à une solution au travail.",
                "Tu vas apprendre une idée brillante en lisant un message.",
                "Prépare-toi à un message important ce soir.",
                "Tu vas rencontrer une opportunité inattendue au détour d'une conversation.",
                "Tu vas éviter une erreur à corriger en faisant du sport.",
                "Il se peut que tu rencontres un regain d'énergie au travail.",
                "Tu vas recevoir une surprise agréable devant un café.",
                "Quelqu'un va te parler d'un souvenir important ce soir.",
                "Tu pourrais ressentir une solution dans la matinée.",
                "Tu vas découvrir un défi à relever au travail.",
                "Aujourd'hui, attends-toi à un moment de calme grâce à un ami.",
                "Tu vas gagner une coïncidence troublante en ligne.",
                "Tu vas rencontrer un message important cet après-midi.",
                "Tu vas éviter un obstacle à franchir en te promenant.",
                "Tu vas apprendre une réflexion personnelle pendant un appel.",
                "Il est probable que tu vives une surprise par hasard.",
                "Tu vas découvrir un sourire sincère au détour d'une conversation.",
                "Tu pourrais ressentir un souvenir marquant ce soir.",
                "Quelqu'un va te parler d'un regain d'énergie au travail.",
                "Aujourd'hui, attends-toi à une bonne nouvelle dans la matinée.",
                "Tu vas éviter un malentendu grâce à un ami.",
                "Prépare-toi à une idée brillante en lisant un message.",
                "Tu vas recevoir une solution inattendue ce soir.",
                "Tu vas gagner un compliment mérité au travail.",
                "Il se peut que tu rencontres une personne inspirante pendant un appel.",
                "Tu vas découvrir un moment de calme en te promenant.",
                "Tu vas rencontrer une surprise agréable dans un rêve.",
                "Un événement inattendu impliquera un message important en ligne.",
                "Tu vas apprendre une nouvelle rencontre cet après-midi.",
                "Aujourd'hui, attends-toi à un souvenir marquant en faisant du sport.",
                "Prépare-toi à vivre une opportunité unique ce soir.",
                "Tu vas recevoir un appel inattendu au détour d'une conversation.",
                "Tu vas éviter un problème mineur pendant un appel.",
                "Tu vas découvrir une idée brillante dans la matinée.",
                "Tu pourrais ressentir un regain d'énergie grâce à un ami.",
                "Une bonne surprise t'attend au détour d'une conversation.",
                "Tu vas croiser quelqu'un qui marquera ta journée.",
                "Un petit imprévu rendra ton après-midi plus vivant.",
                "Une idée brillante surgira pendant une pause café.",
                "Tu recevras un message qui fera sourire.",
                "Une discussion anodine aura un impact inattendu.",
                "Tu ressentiras une montée d'énergie en début de journée.",
                "Quelqu'un te remerciera sincèrement aujourd'hui.",
                "Un souvenir te reviendra en tête et changera ton humeur.",
                "Une décision importante sera plus facile que prévu.",
                "Un détail te fera voir les choses autrement.",
                "Une rencontre légère te donnera de grandes idées.",
                "Tu seras surpris par la gentillesse d'un inconnu.",
                "Un échange te motivera à finir un projet.",
                "Tu retrouveras confiance grâce à une petite réussite.",
                "Une musique entendue par hasard t'inspirera.",
                "Un malentendu trouvera enfin sa solution.",
                "Un moment calme t'apportera une réponse que tu attends.",
                "Quelqu'un te dira quelque chose d'important sans le savoir.",
                "Une opportunité se présentera dans un cadre inattendu.",
                "Tu verras clair dans une situation confuse.",
                "Un geste simple aura de grandes conséquences.",
                "Tu feras une découverte qui simplifiera ton quotidien.",
                "Une tâche banale sera source de satisfaction.",
                "Un compliment sincère viendra éclairer ta journée.",
                "Un défi mineur te fera grandir plus que prévu.",
                "Tu feras rire quelqu'un sans t'en rendre compte.",
                "Un petit effort portera de grands fruits.",
                "Une hésitation deviendra une belle prise d'initiative.",
                "Tu comprendras enfin quelque chose qui t'échappait.",
                "Une phrase entendue te donnera envie d'agir.",
                "Tu créeras du lien avec quelqu'un que tu connais peu.",
                "Un oubli jouera finalement en ta faveur.",
                "Une routine sera brisée pour le meilleur.",
                "Une contrainte deviendra une chance.",
                "Un regard échangé t'apportera du réconfort.",
                "Tu aideras quelqu'un sans le réaliser.",
                "Une surprise te fera changer tes plans.",
                "Un détail ignoré aura son importance.",
                "Tu feras la paix avec un souvenir.",
                "Une nouvelle te rendra curieux aujourd'hui.",
                "Tu prendras une décision sans regrets.",
                "Une discussion éveillera une passion oubliée.",
                "Un mot entendu te donnera de la force.",
                "Une rencontre imprévue te motivera.",
                "Un petit événement changera ton humeur.",
                "Tu trouveras un sens à ce qui te semblait flou.",
                "Une information entendue au hasard te servira bientôt.",
                "Tu auras un moment de clarté en pleine action.",
                "Une distraction te mènera à une bonne surprise.",
                "Une erreur se transformera en bonne décision.",
                "Tu auras un élan d'enthousiasme contagieux.",
                "Tu inspireras quelqu'un sans le vouloir.",
                "Un événement mineur aura une portée symbolique.",
                "Un imprévu viendra rompre une routine pesante.",
                "Tu reconnaîtras ta chance dans un petit détail.",
                "Une tâche repoussée sera accomplie facilement.",
                "Tu retrouveras le sourire grâce à un souvenir heureux.",
                "Une action spontanée te portera chance.",
                "Une impression étrange se confirmera dans la journée.",
                "Tu t'étonneras de ta propre persévérance.",
                "Un silence te dira beaucoup de choses.",
                "Tu seras plus écouté que tu ne le penses.",
                "Une question trouvera sa réponse naturellement.",
                "Tu résoudras un problème presque sans effort.",
                "Une pause te fera gagner du temps.",
                "Une nouvelle habitude commencera aujourd'hui.",
                "Un regard bienveillant suffira à te rassurer.",
                "Un chemin inhabituel t'apportera une surprise.",
                "Tu feras preuve d'un calme inhabituel.",
                "Une conversation sera plus profonde qu'attendu.",
                "Un souvenir d'enfance refera surface de façon inattendue.",
                "Une intuition se confirmera dans les faits.",
                "Un geste anodin aura un grand effet.",
                "Une personne distante se rapprochera.",
                "Une réponse que tu attends viendra par un autre biais.",
                "Tu verras plus loin que d'habitude.",
                "Un effort passé sera enfin reconnu.",
                "Tu avanceras sans t'en rendre compte.",
                "Une rencontre anodine deviendra marquante.",
                "Une envie soudaine t'amènera une belle découverte.",
                "Une journée ordinaire révélera une émotion forte.",
                "Tu agiras avec plus d'assurance que prévu.",
                "Une bonne surprise arrivera quand tu ne l'attendras pas.",
                "Un message oublié refera surface avec du sens.",
                "Un rêve deviendra plus clair à ton réveil.",
                "Un malentendu t'apprendra quelque chose sur toi.",
                "Un besoin intérieur trouvera son exutoire.",
                "Une routine sera allégée aujourd'hui.",
                "Un sourire croisé au hasard changera ta journée.",
                "Tu réaliseras que tu es plus prêt que tu ne le crois.",
                "Un problème passera au second plan sans raison.",
                "Une envie oubliée reviendra en force.",
                "Un contact perdu refera surface.",
                "Un doute se dissipera naturellement.",
                "Tu t'ouvriras à une nouvelle idée sans effort.",
                "Une attente sera récompensée sous une autre forme.",
                "Un moment d'ennui sera fécond.",
                "Une vieille peur te semblera ridicule.",
                "Un regard intérieur t'apportera de la clarté.",
                "Une erreur ancienne cessera de peser.",
                "Un échange bref te nourrira toute la journée.",
                "Une personne familière aura un visage nouveau.",
                "Une sensation agréable viendra sans prévenir.",
                "Tu te sentiras plus libre que d'habitude.",
                "Un appel inattendu ravivera une connexion.",
                "Tu seras étonné par ta propre patience.",
                "Une personne discrète te partagera un secret.",
                "Tu verras une solution là où il n'y en avait pas hier.",
                "Un objet perdu réapparaîtra au bon moment.",
                "Un événement simple te donnera une grande joie.",
                "Une odeur familière éveillera des souvenirs.",
                "Un rire t'aidera à relativiser un tracas.",
                "Une coïncidence attirera ton attention.",
                "Tu recevras un signe clair de ce que tu dois faire.",
                "Une porte que tu croyais fermée s'entrouvrira.",
                "Quelqu'un t'écoutera plus profondément que d'habitude.",
                "Une réponse viendra sans même poser la question.",
                "Tu trouveras du réconfort dans un lieu ordinaire.",
                "Un silence partagé t'apaisera.",
                "Une tâche commencée te portera toute la journée.",
                "Tu remarqueras un détail qui t'avait échappé depuis longtemps.",
                "Une voix intérieure te guidera.",
                "Une conversation interrompue reprendra naturellement.",
                "Un geste spontané t'ouvrira une possibilité.",
                "Tu verras le bon côté d'un contretemps.",
                "Une lumière douce changera ton humeur.",
                "Tu réaliseras que tu es déjà sur le bon chemin.",
                "Une attente deviendra une opportunité.",
                "Un projet laissé de côté refera surface.",
                "Tu inspireras une idée à quelqu'un sans le savoir.",
                "Un compliment te semblera plus sincère que d'habitude.",
                "Une surprise douce viendra d'un collègue ou camarade.",
                "Une décision prise hier montrera déjà ses effets.",
                "Une personne changera ton regard sur une situation.",
                "Une gêne passagère se transformera en soulagement.",
                "Tu reconnaîtras un signe que tu as souvent ignoré.",
                "Une météo inhabituelle changera tes plans.",
                "Une chanson entendue au hasard définira ton humeur.",
                "Un événement prévu sera plus fluide que prévu.",
                "Tu ressentiras un regain d'envie.",
                "Un besoin ancien sera enfin comblé.",
                "Une personne de ton entourage sera d'un grand soutien.",
                "Une fatigue se dissipera sans effort.",
                "Tu découvriras une nouvelle manière de faire.",
                "Un geste du passé trouvera son sens aujourd'hui.",
                "Tu t'exprimeras mieux que d'habitude.",
                "Une rencontre t'ouvrira une nouvelle perspective.",
                "Une émotion refoulée trouvera une issue saine.",
                "Un chemin souvent emprunté te paraîtra nouveau.",
                "Un imprévu rendra ta journée plus belle.",
                "Un défi se transformera en réussite facile.",
                "Un sentiment de justesse t'accompagnera.",
                "Tu auras une prise de conscience soudaine.",
                "Un rendez-vous t'apportera bien plus que prévu.",
                "Une réponse indirecte t'éclairera davantage.",
                "Tu riras d'une situation qui te dérangeait avant.",
                "Tu choisiras la simplicité, et cela te réussira.",
                "Un message oublié trouvera sa signification.",
                "Tu feras une économie inattendue.",
                "Un oubli te sauvera d'un malentendu.",
                "Une lumière extérieure reflétera un état intérieur.",
                "Tu entendras un conseil précieux sans qu'il te soit adressé.",
                "Une relation s'apaisera sans effort.",
                "Tu seras témoin d'un bel acte de générosité.",
                "Une hésitation deviendra une force.",
                "Tu tomberas sur un mot qui résonnera en toi.",
                "Une bonne nouvelle viendra d'un lieu improbable.",
                "Tu reconnaîtras une qualité que tu négligeais en toi.",
                "Un coup de chance discret t'aidera dans une tâche.",
                "Un espace ordinaire deviendra source d'inspiration.",
                "Tu ressentiras une forte envie d'ordre ou de clarté.",
                "Une activité te paraîtra plus plaisante que d'habitude.",
                "Une inquiétude passera plus vite que prévu.",
                "Un visage souriant changera ton énergie.",
                "Tu seras plus productif sans pression.",
                "Une personne t'évitera une erreur sans le savoir.",
                "Une vérité te paraîtra moins lourde aujourd'hui.",
                "Tu commenceras quelque chose que tu finiras bien.",
                "Une route connue prendra un tournant nouveau.",
                "Un instant de solitude t'apportera une belle idée.",
                "Un moment partagé te semblera précieux.",
                "Tu auras envie de remercier quelqu'un spontanément.",
                "Tu ressentiras une force calme en toi.",
                "Une attente te donnera l'occasion de réfléchir.",
                "Un choix ancien te prouvera qu'il était juste.",
                "Un lieu anodin deviendra apaisant.",
                "Tu auras l'intuition de ralentir, et tu feras bien.",
                "Un mot que tu diras réconfortera quelqu'un.",
                "Une bonne énergie circulera autour de toi.",
                "Un événement mineur aura une signification personnelle.",
                "Tu feras confiance à ton instinct, à raison.",
                "Un inconfort se changera en adaptation rapide.",
                "Tu reconnaîtras une chance dans une contrainte.",
                "Un événement te rappellera que tout évolue.",
                "Un oubli volontaire te libérera.",
                "Tu feras le tri, intérieurement ou physiquement.",
                "Un changement de dernière minute sera bénéfique.",
                "Tu te sentiras à ta place dans un contexte nouveau.",
                "Une parole que tu entendras t'encouragera à continuer.",
                "Un changement subtil apportera du renouveau.",
                "Tu laisseras aller quelque chose, et tu te sentiras mieux.",
                "Un sourire spontané attirera une bonne énergie.",
                "Tu prendras de la hauteur sur un problème ancien.",
                "Une rencontre sera courte mais marquante.",
                "Un effort sincère sera remarqué.",
                "Un mal pour un bien se révélera très vite.",
                "Tu sentiras que quelque chose de bon commence."
            ]

        letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
    'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
    'U', 'V', 'W', 'X', 'Y', 'Z']

        phrases_used = []
        results = []

        for letter in letters:
            
            phrase = random.choice(phrases)
            while phrase in phrases_used:
                phrase = random.choice(phrases)
            
            results.append(OneLetterOneSentence(letter, phrase))

        return results