name: Run main.py every day at midnight

on:
  schedule:
    - cron: '0 21 * * *'  # Tous les jours à minuit UTC (donc 2h du matin en France l'été)
  workflow_dispatch:     # Permet aussi de le lancer manuellement

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # permet de réutiliser GITHUB_TOKEN pour git push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # ou la version que tu utilises
    
      - name: Recreate config.json
        run: |
          echo '${{ secrets.CONFIG_JSON }}' > config.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py
      
      - name: Commit updated counter
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add counter.txt
          git commit -m "Incrément du compteur automatique"
          git push
